// Package setup provides generic agent-callable utilities for naitv-mcp.
//
// Stack-specific setup (rules, workflows, and verification tools for a given
// language) is handled by plugins — see internal/plugin and plugins/.
// This package contains the utilities that remain useful regardless of stack:
//   - SetProject: bulk-update working_dir on executable tool entries
//   - ContinueConfig: generate a .continue/config.yaml for this server
//   - ResolveDir: expand ~ and make a path absolute
package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/madicen/naitv-mcp/internal/store"
	"github.com/madicen/naitv-mcp/internal/tools"
)

// SetProjectResult summarises what SetProject changed.
type SetProjectResult struct {
	Updated []string // tool names whose working_dir was updated
	Skipped []string // tool names already pointing at the right directory
}

// SetProject bulk-updates the working_dir field on all active executable tool
// entries. This is a direct write (not a proposal) because it is low-risk and
// the user explicitly requested it through the agent.
func SetProject(st *store.Store, projectDir string, enableLint, disableLint bool) (SetProjectResult, error) {
	entries, err := st.List("tool", nil)
	if err != nil {
		return SetProjectResult{}, fmt.Errorf("list tool entries: %w", err)
	}

	var result SetProjectResult
	for _, e := range entries {
		if !tools.IsExecutable(e) {
			continue
		}
		if e.Fields == nil {
			e.Fields = map[string]string{}
		}

		changed := false
		if e.Fields["working_dir"] != projectDir {
			e.Fields["working_dir"] = projectDir
			changed = true
		}
		if e.Name == "lint" {
			if enableLint && e.Fields["disabled"] != "false" {
				e.Fields["disabled"] = "false"
				changed = true
			} else if disableLint && e.Fields["disabled"] != "true" {
				e.Fields["disabled"] = "true"
				changed = true
			}
		}

		if !changed {
			result.Skipped = append(result.Skipped, e.Name)
			continue
		}
		if _, err := st.Update(e); err != nil {
			return result, fmt.Errorf("update %q: %w", e.Name, err)
		}
		result.Updated = append(result.Updated, e.Name)
	}
	return result, nil
}

// ContinueConfig generates the text of a .continue/config.yaml file wired to
// use the running naitv-mcp server. toolNames is the list of registered
// executable tool names to document in comments. binaryPath is the absolute
// path to the naitv-mcp binary (use os.Executable() at call site).
func ContinueConfig(toolNames []string, binaryPath string) string {
	toolList := "  # (no executable tools registered yet — install a plugin or add tool entries)"
	if len(toolNames) > 0 {
		lines := make([]string, len(toolNames))
		for i, n := range toolNames {
			lines[i] = "  #   " + n
		}
		toolList = strings.Join(lines, "\n")
	}

	return fmt.Sprintf(`# Continue configuration — generated by naitv-mcp
# Docs: https://docs.continue.dev/reference/config

# ── Models ─────────────────────────────────────────────────────────────────────
models:
  - name: local-model
    provider: ollama          # change to: lmstudio | llamacpp | openai | anthropic | …
    model: qwen2.5-coder:14b  # replace with your model name

# ── MCP servers ────────────────────────────────────────────────────────────────
# naitv-mcp exposes your knowledge base and executable tools over the MCP protocol.
# The model calls initialize at session start to receive standing instructions,
# then calls build/vet/test/… autonomously during the verification loop.
#
mcpServers:
  - name: naitv-mcp
    command: %s
    args: ["serve"]

# Executable tools currently in naitv-mcp (pending approval may add more):
%s

# ── System message ─────────────────────────────────────────────────────────────
systemMessage: |
  You are a careful Go engineer working inside Continue.

  SESSION START: Call the initialize tool from naitv-mcp before doing anything
  else. Follow every rule and workflow it returns for the rest of this session.

  VERIFICATION LOOP: After any code change, run the verification sequence
  (build → vet → test) before declaring work done. Fix failures and re-run.
  Do not ask the user to run checks. Do not say "done" until all pass.

  HILL CLIMBING: After completing a task, call search_entries to check whether
  the knowledge base already covers what you learned. If not, call add_entry
  to propose the lesson. The user reviews proposals in the naitv-mcp TUI.

# ── Slash commands ─────────────────────────────────────────────────────────────
# customCommands:
#   - name: setup-project
#     description: Point naitv-mcp tools at this project
#     prompt: |
#       Call install_plugin with source="loop-engineering-go" (or another plugin),
#       then set_project with the current project directory, then generate_continue_config
#       and show me the result so I can save it as .continue/config.yaml.
#
#   - name: reinit
#     description: Reload naitv-mcp standing instructions
#     prompt: Call the initialize tool from naitv-mcp and summarise the rules.
`, binaryPath, toolList)
}

// ResolveDir resolves a directory path: expands ~, makes absolute, and confirms
// the path exists. Returns "" unchanged (callers treat "" as "unset").
func ResolveDir(path string) (string, error) {
	if path == "" {
		return "", nil
	}
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("expand ~: %w", err)
		}
		path = filepath.Join(home, path[1:])
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve path: %w", err)
	}
	if _, err := os.Stat(abs); err != nil {
		return "", fmt.Errorf("path does not exist: %s", abs)
	}
	return abs, nil
}

