// Package setup provides generic agent-callable utilities for naitv-mcp.
//
// Stack-specific setup (rules, workflows, and verification tools for a given
// language) is handled by plugins — see internal/plugin and plugins/.
// This package contains the utilities that remain useful regardless of stack:
//   - SetProject: restore/update working_dir on executable tool entries
//   - ContinueConfig: generate a .continue/config.yaml for this server
//   - ResolveDir: expand ~ and make a path absolute
package setup

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/madicen/naitv-mcp/internal/store"
	"github.com/madicen/naitv-mcp/internal/tools"
	"github.com/madicen/naitv-mcp/internal/xpath"
	"github.com/madicen/naitv-mcp/pkg/entry"
)

// ProjectRootPlaceholder is the working_dir template for tools that take a
// project_root parameter. Agents pass the path per call; set_project must not
// replace this with a baked absolute path.
const ProjectRootPlaceholder = "{project_root}"

// SetProjectResult summarises what SetProject changed.
type SetProjectResult struct {
	Updated []string // tool names whose working_dir (or lint flag) was updated
	Skipped []string // tool names already correct
}

// SetProject updates executable tool entries for the given project.
//
// Tools that declare a project_root parameter keep working_dir="{project_root}"
// so each build/vet/test call can target any repo. Other tools get working_dir
// set to the absolute projectDir. Optionally toggles the lint tool's disabled flag.
//
// This is a direct write (not a proposal) because it is low-risk and the user
// explicitly requested it through the agent.
func SetProject(st *store.Store, projectDir string, enableLint, disableLint bool) (SetProjectResult, error) {
	entries, err := st.List("tool", nil)
	if err != nil {
		return SetProjectResult{}, fmt.Errorf("list tool entries: %w", err)
	}

	var result SetProjectResult
	for _, e := range entries {
		if !tools.IsExecutable(e) {
			continue
		}
		if e.Fields == nil {
			e.Fields = map[string]string{}
		}

		targetDir := projectDir
		if usesProjectRootParam(e) {
			targetDir = ProjectRootPlaceholder
		}

		changed := false
		if e.Fields["working_dir"] != targetDir {
			e.Fields["working_dir"] = targetDir
			changed = true
		}
		if e.Name == "lint" {
			if enableLint && e.Fields["disabled"] != "false" {
				e.Fields["disabled"] = "false"
				changed = true
			} else if disableLint && e.Fields["disabled"] != "true" {
				e.Fields["disabled"] = "true"
				changed = true
			}
		}

		if !changed {
			result.Skipped = append(result.Skipped, e.Name)
			continue
		}
		if _, err := st.Update(e); err != nil {
			return result, fmt.Errorf("update %q: %w", e.Name, err)
		}
		result.Updated = append(result.Updated, e.Name)
	}
	return result, nil
}

// usesProjectRootParam reports whether the tool expects a project_root argument
// (loop-engineering-go style) rather than a baked absolute working_dir.
func usesProjectRootParam(e entry.Entry) bool {
	if strings.Contains(e.Fields["working_dir"], ProjectRootPlaceholder) {
		return true
	}
	raw := strings.TrimSpace(e.Fields["params"])
	if raw == "" {
		return false
	}
	var params []tools.Param
	if err := json.Unmarshal([]byte(raw), &params); err != nil {
		return strings.Contains(raw, `"name":"project_root"`) || strings.Contains(raw, `"name": "project_root"`)
	}
	for _, p := range params {
		if p.Name == "project_root" {
			return true
		}
	}
	return false
}

// ContinueConfig generates the text of a .continue/config.yaml file wired to
// use the running naitv-mcp server. toolNames is the list of registered
// executable tool names to document in comments. binaryPath is the absolute
// path to the naitv-mcp binary (use os.Executable() at call site).
func ContinueConfig(toolNames []string, binaryPath string) string {
	toolList := "  # (no executable tools registered yet — install a plugin or add tool entries)"
	if len(toolNames) > 0 {
		lines := make([]string, len(toolNames))
		for i, n := range toolNames {
			lines[i] = "  #   " + n
		}
		toolList = strings.Join(lines, "\n")
	}

	return fmt.Sprintf(`# Continue configuration — generated by naitv-mcp
# Docs: https://docs.continue.dev/reference/config

# ── Models ─────────────────────────────────────────────────────────────────────
models:
  - name: local-model
    provider: ollama          # change to: lmstudio | llamacpp | openai | anthropic | …
    model: qwen2.5-coder:14b  # replace with your model name

# ── MCP servers ────────────────────────────────────────────────────────────────
# naitv-mcp exposes your knowledge base and executable tools over the MCP protocol.
# The model calls initialize at session start to receive standing instructions,
# then calls build/vet/test/… autonomously during the verification loop.
#
mcpServers:
  - name: naitv-mcp
    command: %s
    args: ["serve"]

# Executable tools currently in naitv-mcp (pending approval may add more):
%s

# ── System message ─────────────────────────────────────────────────────────────
systemMessage: |
  You are a careful Go engineer working inside Continue.

  SESSION START: Call the initialize tool from naitv-mcp before doing anything
  else. Follow every rule and workflow it returns for the rest of this session.

  VERIFICATION LOOP: After any code change, run the verification sequence
  (build → vet → test) before declaring work done. Fix failures and re-run.
  Do not ask the user to run checks. Do not say "done" until all pass.

  HILL CLIMBING: After completing a task, call search_entries to check whether
  the knowledge base already covers what you learned. If not, call add_entry
  to propose the lesson. The user reviews proposals in the naitv-mcp TUI.

# ── Slash commands ─────────────────────────────────────────────────────────────
# customCommands:
#   - name: setup-project
#     description: Point naitv-mcp tools at this project
#     prompt: |
#       Call install_plugin with source="loop-engineering-go" (or another plugin),
#       then set_project with the current project directory, then generate_continue_config
#       and show me the result so I can save it as .continue/config.yaml.
#
#   - name: reinit
#     description: Reload naitv-mcp standing instructions
#     prompt: Call the initialize tool from naitv-mcp and summarise the rules.
`, binaryPath, toolList)
}

// ResolveDir resolves a directory path: expands ~, makes absolute, and confirms
// the path exists. Returns "" unchanged (callers treat "" as "unset").
func ResolveDir(path string) (string, error) {
	if path == "" {
		return "", nil
	}
	path = xpath.ExpandHome(path)
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve path: %w", err)
	}
	if _, err := os.Stat(abs); err != nil {
		return "", fmt.Errorf("path does not exist: %s", abs)
	}
	return abs, nil
}

